name: Generate ASCII Artwork
on: push
jobs:
  generate:
    name: Generate the file
    runs-on: ubuntu-24.04
    steps:
      - name: Install and execute Cowsay program
        run: |
          sudo apt-get install cowsay -y
          cowsay -f dragon "I'm the King Lion" >> lion.txt
      - name: Upload the artifact
        uses: actions/upload-artifact@v5
        with:
          name: lion-artifact
          path: artifacts/file.txt
      - name: List content  of the repo
        run: ls -ltra
  test:
    name: Test the generated file
    runs-on: ubuntu-24.04
    needs: generate
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v5
        with:
          name: lion-artifact
      - name: Make sure that the file is present
        run: test file.txt
      - name: Display and test the content of the file
        run: |
          cat file.txt
          cat file.txt | grep "King Lion"
